// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination mock_metrics.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// Consumed mocks base method.
func (m *MockMetrics) Consumed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Consumed")
}

// Consumed indicates an expected call of Consumed.
func (mr *MockMetricsMockRecorder) Consumed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consumed", reflect.TypeOf((*MockMetrics)(nil).Consumed))
}

// Processed mocks base method.
func (m *MockMetrics) Processed() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Processed")
}

// Processed indicates an expected call of Processed.
func (mr *MockMetricsMockRecorder) Processed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Processed", reflect.TypeOf((*MockMetrics)(nil).Processed))
}

// Requested mocks base method.
func (m *MockMetrics) Requested() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Requested")
}

// Requested indicates an expected call of Requested.
func (mr *MockMetricsMockRecorder) Requested() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Requested", reflect.TypeOf((*MockMetrics)(nil).Requested))
}

// Response mocks base method.
func (m *MockMetrics) Response(status int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Response", status)
}

// Response indicates an expected call of Response.
func (mr *MockMetricsMockRecorder) Response(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Response", reflect.TypeOf((*MockMetrics)(nil).Response), status)
}
