// Package maelstrom provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package maelstrom

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// Node defines model for Node.
type Node struct {
	Addr *string        `json:"Addr,omitempty"`
	Name *string        `json:"Name,omitempty"`
	Port *int           `json:"Port,omitempty"`
	Tags *[]interface{} `json:"Tags,omitempty"`
}

// Scale defines model for Scale.
type Scale struct {
	NumberOfWorkers *int `json:"number_of_workers,omitempty"`
}

// ScaleJSONRequestBody defines body for Scale for application/json ContentType.
type ScaleJSONRequestBody = Scale
