// Package maelstrom provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package maelstrom

// Node defines model for Node.
type Node struct {
	Addr *string        `json:"Addr,omitempty"`
	Name *string        `json:"Name,omitempty"`
	Port *int           `json:"Port,omitempty"`
	Tags *[]interface{} `json:"Tags,omitempty"`
}

// Scale defines model for Scale.
type Scale struct {
	NumberOfWorkers *int `json:"number_of_workers,omitempty"`
}

// Status defines model for Status.
type Status struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// Vortex defines model for Vortex.
type Vortex struct {
	Host string `json:"host"`
}

// ScaleJSONRequestBody defines body for Scale for application/json ContentType.
type ScaleJSONRequestBody = Scale

// StartJSONRequestBody defines body for Start for application/json ContentType.
type StartJSONRequestBody = Vortex

// StopJSONRequestBody defines body for Stop for application/json ContentType.
type StopJSONRequestBody = Status
