// Package maelstrom provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package maelstrom

// Node defines model for Node.
type Node struct {
	Addr *string        `json:"Addr,omitempty"`
	Name *string        `json:"Name,omitempty"`
	Port *int           `json:"Port,omitempty"`
	Tags *[]interface{} `json:"Tags,omitempty"`
}

// Replicas defines model for Replicas.
type Replicas struct {
	Replicas int `json:"replicas"`
}

// Status defines model for Status.
type Status struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// Vortex defines model for Vortex.
type Vortex struct {
	ConsumerBuffer int     `json:"consumer_buffer"`
	Host           string  `json:"host"`
	Id             *string `json:"id,omitempty"`
	ResultBuffer   int     `json:"result_buffer"`
	Workers        int     `json:"workers"`
}

// ReplicasJSONRequestBody defines body for Replicas for application/json ContentType.
type ReplicasJSONRequestBody = Replicas

// StopJSONRequestBody defines body for Stop for application/json ContentType.
type StopJSONRequestBody = Status

// VortexJSONRequestBody defines body for Vortex for application/json ContentType.
type VortexJSONRequestBody = Vortex
