openapi: "3.0.0"
info:
  version: 0.0.2
  title: Maelstrom
  description: |-
    open-api spec for Maelstrom
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: 0.0.0.0
paths:
  /nodes:
    get:
      operationId: nodes
      responses:
        '200':
          description: |- 
            get the current set of maelstrom nodes
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Node'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /nodes/{id}:
    get:
      description: |-
        returns a single node based on ID
      operationId: findNodeByID
      parameters:
        - name: id
          in: path
          description: ID of node to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: node response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /healthz:
    get:
      operationId: health
      responses:
        '204':
          description: |-
            kubernetes healthchecks
        default:
          description: error obtaining health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /replicas:
    get:
      operationId: replicas
      responses:
        '200':
          description: |-
            number of Maelstrom replicas
        default:
          description: error obtaining number of Maelstrom replicas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    put:
      operationId: scaleReplicas
      requestBody:
        description: |-
          scale the number of statefulsets through K8s API
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Replicas'
      responses:
        '202':
          description: |-
            kubernetes healthchecks
        default:
          description: error obtaining health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /vortex:
    post:
      operationId: vortex
      requestBody:
        description: |-
         start the load test
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vortex'
      responses:
        '200':
          description: |-
           confirm the test started with the following configuration
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vortex'
        default:
          description: error trying to start load test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
    delete:
      operationId: stop
      requestBody:
        description: stop the load test
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
      responses:
        '200':
          description: |-
            stop the load test
        default:
          description: error trying to start load test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'

components:
  schemas:
    Node:
      type: object
      properties:
        Name:
          type: string
        Addr:
          type: string
        Port:
          type: integer
        Tags:
          type: array
    Replicas:
      type: object
      required: [replicas]
      properties:
        replicas:
          type: integer
    Vortex:
      type: object
      required: [host, jobs, workers, consumer_buffer, result_buffer]
      properties:
        id:
          description: uuid of created load test
          type: string
        host:
          description: host / url to hit
          type: string
        jobs:
          description: number of goroutines consuming / processing. eg 2 jobs will create two consumers + processors
          type: integer
        workers:
          description: |- 
            number of workers per job, remember that IO is blocking on the goroutine, so you can up this and not be CPU 
            throttled. A good starting point on a 8 vcpu machine is 10 jobs, 36 workers. Depending on the target's response 
            time and level of processing needed.
          type: integer
        consumer_buffer:
          description: |- 
            tuneable buffers for the consumer + processor, this can be unbuffered, though buffering may make this
            go faster. But you'd need to change these per workload and manage system memory and contention
          type: integer
        result_buffer:
          description: |-
            same as above, but for the vortexer and result processing.
          type: integer
    Status:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string
