// Code generated by MockGen. DO NOT EDIT.
// Source: agent.go
//
// Generated by this command:
//
//	mockgen -source=agent.go -destination mocks/agent.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	serf "github.com/hashicorp/serf/serf"
	commander "github.com/jonny7/maelstrom/cmd/maelstrom/internal/core/commander"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Members mocks base method.
func (m *MockService) Members() []serf.Member {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members")
	ret0, _ := ret[0].([]serf.Member)
	return ret0
}

// Members indicates an expected call of Members.
func (mr *MockServiceMockRecorder) Members() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockService)(nil).Members))
}

// Start mocks base method.
func (m *MockService) Start(host string, jobs, workers, cbuf, rbuf int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Start", host, jobs, workers, cbuf, rbuf)
}

// Start indicates an expected call of Start.
func (mr *MockServiceMockRecorder) Start(host, jobs, workers, cbuf, rbuf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockService)(nil).Start), host, jobs, workers, cbuf, rbuf)
}

// Stop mocks base method.
func (m *MockService) Stop(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", id)
}

// Stop indicates an expected call of Stop.
func (mr *MockServiceMockRecorder) Stop(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockService)(nil).Stop), id)
}

// Vortexes mocks base method.
func (m *MockService) Vortexes() []commander.Vortex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vortexes")
	ret0, _ := ret[0].([]commander.Vortex)
	return ret0
}

// Vortexes indicates an expected call of Vortexes.
func (mr *MockServiceMockRecorder) Vortexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vortexes", reflect.TypeOf((*MockService)(nil).Vortexes))
}
