openapi: "3.0.0"
info:
  version: 0.0.1
  title: Maelstrom members
  description: |
    open-api spec for Maelstrom
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: 0.0.0.0
paths:
  /nodes:
    get:
      operationId: nodes
      responses:
        '200':
          description: | 
            get the current set of maelstrom nodes
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Node'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /healthz:
    get:
      operationId: health
      responses:
        '204':
          description: |
            kubernetes healthchecks
        default:
          description: error obtaining health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /scale:
    post:
      operationId: scale
      requestBody:
        description: |
          scale the number of nodes through K8s API
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Scale'
      responses:
        '204':
          description: |
            kubernetes healthchecks
        default:
          description: error obtaining health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /start:
    post:
      operationId: start
      requestBody:
        description: |
         start the load test
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vortex'
      responses:
        '200':
          description: |
           acknowledge the test started
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        default:
          description: error trying to start load test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
  /stop:
    post:
      operationId: stop
      requestBody:
        description: |
          stop the load test
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Status'
      responses:
        '200':
          description: |
            stop the load test
        default:
          description: error trying to start load test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'

components:
  schemas:
    Node:
      type: object
      properties:
        Name:
          type: string
        Addr:
          type: string
        Port:
          type: integer
        Tags:
          type: array
    Scale:
      type: object
      required: [numberOfWorkers]
      properties:
        number_of_workers:
          type: integer
    Vortex:
      type: object
      required: [host, workers]
      properties:
        host:
          type: string
        workers:
          type: integer
    Status:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: integer
        message:
          type: string
