apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: maelstrom
  namespace: default
spec:
  serviceName: "maelstrom-svc"
  replicas: 2
  selector:
    matchLabels:
      app: maelstrom
  template:
    metadata:
      labels:
        app: maelstrom
    spec:
      containers:
        - name: maelstrom
          image: localhost:5000/jonny/maelstrom
          imagePullPolicy: Never
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: 3000
          ports:
            - containerPort: 7373
              name: rpc
            - containerPort: 7946
              name: serf
            - containerPort: 3000
              name: api
            - containerPort: 4000
              name: ui
            - containerPort: 2112
              name: metrics