apiVersion: v1
kind: Service
metadata:
  name: maelstrom-svc
spec:
  clusterIP: None
  selector:
    app: maelstrom
  publishNotReadyAddresses: true
  ports:
    - name: rpc
      port: 7373
      targetPort: 7373
    - name: serf-tcp
      protocol: "TCP"
      port: 7946
      targetPort: 7946
    - name: serf-udp
      protocol: "UDP"
      port: 7946
      targetPort: 7946