// Code generated by MockGen. DO NOT EDIT.
// Source: commander.go
//
// Generated by this command:
//
//	mockgen -source=commander.go -destination mocks/commander.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	uuid "github.com/google/uuid"
	commander "github.com/jonny7/maelstrom/internal/core/commander"
	gomock "go.uber.org/mock/gomock"
)

// MockCommand is a mock of Command interface.
type MockCommand struct {
	ctrl     *gomock.Controller
	recorder *MockCommandMockRecorder
}

// MockCommandMockRecorder is the mock recorder for MockCommand.
type MockCommandMockRecorder struct {
	mock *MockCommand
}

// NewMockCommand creates a new mock instance.
func NewMockCommand(ctrl *gomock.Controller) *MockCommand {
	mock := &MockCommand{ctrl: ctrl}
	mock.recorder = &MockCommandMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommand) EXPECT() *MockCommandMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockCommand) Start(host string, jobs, workers, cbuf, rbuf int) commander.Vortex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", host, jobs, workers, cbuf, rbuf)
	ret0, _ := ret[0].(commander.Vortex)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCommandMockRecorder) Start(host, jobs, workers, cbuf, rbuf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCommand)(nil).Start), host, jobs, workers, cbuf, rbuf)
}

// Stop mocks base method.
func (m *MockCommand) Stop(id uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", id)
}

// Stop indicates an expected call of Stop.
func (mr *MockCommandMockRecorder) Stop(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCommand)(nil).Stop), id)
}

// Vortexes mocks base method.
func (m *MockCommand) Vortexes() []commander.Vortex {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vortexes")
	ret0, _ := ret[0].([]commander.Vortex)
	return ret0
}

// Vortexes indicates an expected call of Vortexes.
func (mr *MockCommandMockRecorder) Vortexes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vortexes", reflect.TypeOf((*MockCommand)(nil).Vortexes))
}
