// Code generated by MockGen. DO NOT EDIT.
// Source: ports.go
//
// Generated by this command:
//
//	mockgen -source=ports.go -destination mocks/ports.go -package mock
//

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	commander "github.com/jonny7/maelstrom/internal/core/commander"
	gomock "go.uber.org/mock/gomock"
)

// MockGenerator is a mock of Generator interface.
type MockGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockGeneratorMockRecorder
}

// MockGeneratorMockRecorder is the mock recorder for MockGenerator.
type MockGeneratorMockRecorder struct {
	mock *MockGenerator
}

// NewMockGenerator creates a new mock instance.
func NewMockGenerator(ctrl *gomock.Controller) *MockGenerator {
	mock := &MockGenerator{ctrl: ctrl}
	mock.recorder = &MockGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGenerator) EXPECT() *MockGeneratorMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockGenerator) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockGeneratorMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGenerator)(nil).Close))
}

// Start mocks base method.
func (m *MockGenerator) Start(done <-chan struct{}, buffer int) chan commander.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", done, buffer)
	ret0, _ := ret[0].(chan commander.Event)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockGeneratorMockRecorder) Start(done, buffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockGenerator)(nil).Start), done, buffer)
}

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockProcessor) Process(done chan struct{}, work <-chan commander.Event, host string, buffer int) chan *http.Request {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", done, work, host, buffer)
	ret0, _ := ret[0].(chan *http.Request)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockProcessorMockRecorder) Process(done, work, host, buffer any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProcessor)(nil).Process), done, work, host, buffer)
}

// MockHTTPDoer is a mock of HTTPDoer interface.
type MockHTTPDoer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPDoerMockRecorder
}

// MockHTTPDoerMockRecorder is the mock recorder for MockHTTPDoer.
type MockHTTPDoerMockRecorder struct {
	mock *MockHTTPDoer
}

// NewMockHTTPDoer creates a new mock instance.
func NewMockHTTPDoer(ctrl *gomock.Controller) *MockHTTPDoer {
	mock := &MockHTTPDoer{ctrl: ctrl}
	mock.recorder = &MockHTTPDoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPDoer) EXPECT() *MockHTTPDoerMockRecorder {
	return m.recorder
}

// Do mocks base method.
func (m *MockHTTPDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Do indicates an expected call of Do.
func (mr *MockHTTPDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockHTTPDoer)(nil).Do), req)
}
