// Code generated by MockGen. DO NOT EDIT.
// Source: logging.go
//
// Generated by this command:
//
//	mockgen -source=logging.go -destination mock_logger.go -package mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	logging "github.com/jonny7/maelstrom/internal/logging"
	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Log mocks base method.
func (m *MockLogger) Log(level logging.LogLevel, msg string, kv ...logging.KV) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg}
	for _, a := range kv {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Log", varargs...)
}

// Log indicates an expected call of Log.
func (mr *MockLoggerMockRecorder) Log(level, msg any, kv ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg}, kv...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Log", reflect.TypeOf((*MockLogger)(nil).Log), varargs...)
}

// LogWithError mocks base method.
func (m *MockLogger) LogWithError(level logging.LogLevel, msg string, e error, kv ...logging.KV) {
	m.ctrl.T.Helper()
	varargs := []any{level, msg, e}
	for _, a := range kv {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "LogWithError", varargs...)
}

// LogWithError indicates an expected call of LogWithError.
func (mr *MockLoggerMockRecorder) LogWithError(level, msg, e any, kv ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{level, msg, e}, kv...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogWithError", reflect.TypeOf((*MockLogger)(nil).LogWithError), varargs...)
}
